data_path:
  no_var: !!set
     man_01.bag: null
     mix_1.bag: null
     auto_01.bag: null
  var: !!set
    man_21.bag: null
    mix_2.bag: null
    auto_01.bag: null
    auto_21.bag: null
  #rail: !!set
  #  1.bag: null
  #  2.bag: null
  #  3.bag: null
gp_method: ME         # Input uncertainty method, ME = mean equiv, TA = taylor approx
simplify_cov_axis: 2  # Which axis to use for the reduced cov, default 0

mean_func: zero
hyper:                # Following Rasmussen2006
  length_scale: 0.10   # \ell 
  noise_var: 12.5      # \sigma_n^2 
  signal_var: 0.25     # \sigma_f^2
  mean: 0.0   # constant value of mean function
  linear: 0.0 # slope of the mean function
  hinge: 0.0  # position of the elbow/corner of the ReLU/Hinge

hyper_rot:
  length_scale: 0.20
  noise_var: 14.0
  signal_var: 1.8

model_path: GP_models.pkl
num_model_points: 50

num_sparse_points: 0
trim_thresh_force: 0.0 # Data with force less than this are removed 
trim_thresh_init: 0.05 # Data within this distance of init are removed
trim_workspace: 1.0 #0.43   # Data with z value higher than this are removed

obs_noise: 0.1 # covariance of noise added to the observations

opt_hyper: true
print_hyper: false
plot: false
plot_data: false
plot_linear: true
plot_extension: 0.1
