
#### COST FUNCTION PARAMETERS  ####
H: 0         # Force cost
I: 1000      # Force covariance cos
Q_vel: 0.0   # Velocity cost
S: 0.0     # State covariance cost
R: 0.01     # Contol cost

imp_mass: 5
delta_K_max: 10
delta_K_cost: 0.1
K_min: 0.001
K_max: 400
K_cost: 0.0001

delta_xd_max: 0.01

Rr: 70.0    # Rotational control cost
u_rot_max: 6.0 # Max rotational force (Nm)


match_human_force: true     # Cost function penalizes |f_human -j u| instead of |f_human|
match_force_setpoint: 0
match_force_setpoint_weight: 0


#### MPC Problem ####
opti_MBK: true             # Jointly optimize M/B/K params
enable_rotation: false

state_cov: true            # Consider the state covariance
simplify_cov: false          # Use only  first element in GP covariance, axis specified in gp_params

mpc_pts: 15
dt: 0.09
constraint_slack: 0.0
bound_relax_factor: 1e-5

sim: false

#### Outputs and debug ####
print_control: true
live_plot: false    # display the trajectory planning, pretty big perf reduction
